require "gonzo.options"
require "gonzo.keymaps"
require "gonzo.plugins"
require "gonzo.colorscheme"
require "gonzo.cmp"
require "gonzo.lsp"
require "gonzo.telescope"
require "gonzo.treesitter"
require "gonzo.comment"
require "gonzo.gitsigns"
require "gonzo.nvim-tree"
require "gonzo.bufferline"
require "gonzo.lualine"
require "gonzo.indentline"
require "gonzo.autocommands"

-- NOPE
-- require "gonzo.project"
-- require "gonzo.impatient"
-- require "gonzo.autopairs"
-- require "gonzo.toggleterm"
-- require "gonzo.alpha"
-- require "gonzo.whichkey"
